baseURL = "http://roleplayinggamescast.com/"
languageCode = "en-us"
title = "Role Playing GamesCast"
#theme = "hugo_theme_beg"
#theme = "hugo-theme-pixyll"
#theme = "hugo-base16-theme"
theme = "RPGC"
#theme = "after-dark"
#theme = "minimo"
uglyurls = false

[params]
  navTitle = "Home"
